In [5]:
students = ['张三', '李四', '王五', '赵六', '周七']
print('学生列表:', students)
print('第一个学生:', students[0])
print('第二个学生:', students[1])
print('第三个学生:', students[2])
print('最后一个学生:', students[-1])
print('第一个到第三个学生:', students[0:3])

学生列表: ['张三', '李四', '王五', '赵六', '周七']
第一个学生: 张三
第二个学生: 李四
第三个学生: 王五
最后一个学生: 周七
第一个到第三个学生: ['张三', '李四', '王五']


In [ ]:
# 字典示例：单个学生成绩
score_zhang = {
    '姓名': '张三',
    '语文': 78,
    '数学': 85,
    '英语': 90
}
print('张三数学成绩:', score_zhang['数学'])
print('张三语文成绩:', score_zhang['语文'])
print('张三英语成绩:', score_zhang['英语'])

张三数学成绩: 85
张三语文成绩: 78
张三英语成绩: 90


In [7]:
# 元组示例：保存 5 个学生姓名（不可修改）
students_tuple = ('张三', '李四', '王五', '赵六', '周七')
print('学生元组:', students_tuple)
print('第一个学生:', students_tuple[0])
print('第二个学生:', students_tuple[1])
print('第三个学生:', students_tuple[2])
print('最后一个学生:', students_tuple[-1])
print('第一个到第三个学生:', students_tuple[0:3])

学生元组: ('张三', '李四', '王五', '赵六', '周七')
第一个学生: 张三
第二个学生: 李四
第三个学生: 王五
最后一个学生: 周七
第一个到第三个学生: ('张三', '李四', '王五')


In [8]:
students_tuple[0] = '李四'  # 这行代码会引发错误，因为元组不可修改


TypeError: 'tuple' object does not support item assignment

In [9]:
students[0] = '李四'  # 这行代码是合法的，因为列表是可修改的
print('修改后的学生列表:', students)

修改后的学生列表: ['李四', '李四', '王五', '赵六', '周七']


In [18]:
import re
s = 'NIUMA2007/07/22'
re.sub(r'(\d{4})/(\d{2})/(\d{2})', r'\1-\2-\3', s)

'NIUMA2007-07-22'

In [19]:
# range 三种示例
a = range(5)
b = range(5, 10)   
c = range(0, 10, 2) # 0~10 步长为 2
print(a)

range(0, 5)


In [20]:
# 创建成绩'表'：列表中包含多个学生记录（字典）
grade_table = [
    {'姓名': '张三', '语文': 78, '数学': 85, '英语': 90},
    {'姓名': '李四', '语文': 82, '数学': 88, '英语': 76},
    {'姓名': '王五', '语文': 90, '数学': 92, '英语': 89},
    {'姓名': '赵六', '语文': 67, '数学': 74, '英语': 70},
    {'姓名': '周七', '语文': 88, '数学': 79, '英语': 84},
]

In [21]:
[row['语文'] for row in grade_table]

[78, 82, 90, 67, 88]

In [23]:
chinese = []
for row in grade_table:
    chinese.append(row['语文']) 
print('语文成绩列表:', chinese)

语文成绩列表: [78, 82, 90, 67, 88]


In [24]:
# 函数与异常示例
def average_three(a, b, c):
    return (a + b + c) / 3


print('张三平均分:', average_three(78, 85, 90))
# 故意制造一个类型错误
print('错误示例:', average_three(78, '85', 90))


张三平均分: 84.33333333333333


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [30]:
# 函数与异常示例
def average_three(a, b, c):
    return (a + b + c) / 3

a = []
i = 0
while len(a) < 3:
    try:
        a.append(float(input(f'请输入第{i+1}个学生的平均分: ')))
        i += 1
    except ValueError:
        print('输入无效，请输入一个有效的数字。')
print('学生平均分列表:', average_three(a[0], a[1], a[2]))

输入无效，请输入一个有效的数字。
输入无效，请输入一个有效的数字。
学生平均分列表: 3.3333333333333335


In [ ]:
import numpy as np


In [48]:
n = 100000000

In [53]:
sum = 0
for i in range(n):
    sum += i
print(f'0 到 {n-1} 的和是: {sum}')

0 到 99999999 的和是: 4999999950000000


In [55]:
np.sum(np.arange(n))

887459712

In [54]:

np.sum(np.arange(n), dtype=np.int64)

4999999950000000

In [60]:
import math as m
m.sin(0)

0.0

In [61]:
a = [1,2,3]
[m.sin(x) for x in a]

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [62]:
import numpy as np
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [66]:
a = np.array([1, 2, 3, 4])
print('a =', a)
print('-'*30)

a + [1,2]

a = [1 2 3 4]
------------------------------


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [69]:
b = np.array([[1.0, 2, 3], [4, 5, 6]])
print('b =\n', b)
print('-'*30)
# 二维广播
b + [1,2]

b =
 [[1. 2. 3.]
 [4. 5. 6.]]
------------------------------


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 